name: Build and Release Resume

on:
  push:
    paths:
      - resume.yaml
      - resume.j2
      - .github/workflows/generate_resume.yml
      - devenv.nix

env:
  RESUME_NAME: Scott\ Scoble\ Resume

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Resume
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: cachix/install-nix-action@v22
      - uses: cachix/cachix-action@v12
        with:
          name: devenv
      - name: Install devenv.sh
        run: nix profile install tarball+https://install.devenv.sh/latest
        shell: sh

      - run: devenv shell ci
      - name: Rename outputs
        run: |
          mv resume.pdf "$RESUME_NAME".pdf
          mv resume.docx "$RESUME_NAME".docx

      - name: Get next tag
        id: tag
        run: echo "next=$(devenv shell next-tag)" >> $GITHUB_OUTPUT

      - name: Tag commit for release
        uses: rickstaa/action-create-tag@v1
        id: "tag_create"
        with:
          tag: "${{ steps.tag.outputs.next }}"
          tag_exists_error: false
          message: "Latest release"

      - name: Release artifacts
        uses: softprops/action-gh-release@v1
        with:
          files: |
            "$RESUME_NAME.pdf"
            "$RESUME_NAME.docx"